In [1]:
import numpy as np
import pandas as pd

In [2]:
# Load the collated EOSs
collated_eos = pd.read_csv(
    '../data/eos-draws-default/eos-draws-default.csv',
    index_col='eos'
)

In [3]:
collated_eos

,Mmax,logweight_Fonseca_J0740,logweight_Antoniadis_J0348,logweight_Choudhury_J0437,logweight_Miller_J0030,logweight_Miller_J0740,logweight_GW170817,logweight_GW190425,logweight_total,prior_weight
eos,,,,,,,,,,
2265967.0,1.700984,-inf,-inf,9.139681,7.747685,-16.864775,6.864917,10.745082,-inf,1.0
264698.0,1.590114,-inf,-inf,-149.884999,-179.692122,-182.080274,6.529798,8.000491,-inf,1.0
1683176.0,0.402205,-inf,-inf,-inf,-inf,-inf,6.397435,9.827886,-inf,1.0
696150.0,0.860414,-inf,-inf,-inf,-inf,-inf,5.889025,10.090964,-inf,1.0
275937.0,1.236473,-inf,-inf,-534.732271,-325.212510,-570.617845,5.509491,9.061773,-inf,1.0
...,...,...,...,...,...,...,...,...,...,...
280847.0,0.891053,-inf,-inf,-inf,-inf,-inf,6.062024,9.828265,-inf,1.0
459317.0,0.590972,-inf,-inf,-inf,-inf,-inf,6.066148,10.137624,-inf,1.0
2234499.0,1.665527,-inf,-inf,9.328456,8.516454,-27.897028,6.638680,10.012461,-inf,1.0
2285403.0,1.415895,-inf,-inf,-129.169707,-106.205792,-291.337477,7.311489,10.108510,-inf,1.0
1340918.0,0.559531,-inf,-inf,-inf,-inf,-inf,6.177313,9.956582,-inf,1.0

In [4]:
# The maximised likelihood weights
# --------------------------------

# Fixed nterm
for nterm in [2, 3, 4, 5, 6, 7, 8, 9, 10]:

        
    # Marginalized over X
    pqcd_weights = np.loadtxt(f'../data/eos-draws-default/pqcd-weights/pqcd_weights_{nterm:02}nsat_Xmarg_mu2.6.dat')

    # Add the weights to the collated EOSs
    collated_eos.insert(len(collated_eos.columns), f'pqcd_weight_{nterm:02}nsat_Xmarg_mu2.6', pqcd_weights)

    # Fixed X
    for X in [0.5, 2]:
        pqcd_weights = np.loadtxt(f'../data/eos-draws-default/pqcd-weights/pqcd_weights_{nterm:02}nsat_X{X}_mu2.6.dat')

        # Add the weights to the collated EOSs
        collated_eos.insert(len(collated_eos.columns), f'pqcd_weight_{nterm:02}nsat_X{X}_mu2.6', pqcd_weights)

# nterm = nTOV

pqcd_weights = np.loadtxt('../data/eos-draws-default/pqcd-weights/pqcd_weights_ntov_Xmarg_mu2.6.dat')
collated_eos.insert(len(collated_eos.columns), 'pqcd_weight_ntov_Xmarg_mu2.6', pqcd_weights)

for X in [0.5, 2]:
    pqcd_weights = np.loadtxt(f'../data/eos-draws-default/pqcd-weights/pqcd_weights_ntov_X{X}_mu2.6.dat')
    collated_eos.insert(len(collated_eos.columns), f'pqcd_weight_ntov_X{X}_mu2.6', pqcd_weights)

# The marginalized likelihood weights
# -----------------------------------

for nterm in [4, 5, 6, 7, 8, 10]:
    pqcd_weights_marg = np.loadtxt(f'../data/eos-draws-default/pqcd-weights/pqcd_weights_{nterm:02}nsat_marg.dat')
    collated_eos.insert(len(collated_eos.columns), f'pqcd_weight_{nterm:02}nsat_marg', pqcd_weights_marg)
        
# nterm = nTOV
pqcd_weights_marg = np.loadtxt('../data/eos-draws-default/pqcd-weights/pqcd_weights_ntov_marg.dat')
collated_eos.insert(len(collated_eos.columns), 'pqcd_weight_ntov_marg', pqcd_weights_marg)

In [5]:
collated_eos

,Mmax,logweight_Fonseca_J0740,logweight_Antoniadis_J0348,logweight_Choudhury_J0437,logweight_Miller_J0030,logweight_Miller_J0740,logweight_GW170817,logweight_GW190425,logweight_total,prior_weight,...,pqcd_weight_ntov_Xmarg_mu2.6,pqcd_weight_ntov_X0.5_mu2.6,pqcd_weight_ntov_X2_mu2.6,pqcd_weight_04nsat_marg,pqcd_weight_05nsat_marg,pqcd_weight_06nsat_marg,pqcd_weight_07nsat_marg,pqcd_weight_08nsat_marg,pqcd_weight_10nsat_marg,pqcd_weight_ntov_marg
eos,,,,,,,,,,,,,,,,,,,,,
2265967.0,1.700984,-inf,-inf,9.139681,7.747685,-16.864775,6.864917,10.745082,-inf,1.0,...,1.000,1.0,1.0,1.178079,0.961522,0.877837,9.276641e-01,1.070579e+00,7.581512e-01,8.762803e-01
264698.0,1.590114,-inf,-inf,-149.884999,-179.692122,-182.080274,6.529798,8.000491,-inf,1.0,...,0.753,0.0,1.0,0.153030,0.067579,0.096838,6.046293e-02,2.867965e-02,6.772450e-03,4.011288e-04
1683176.0,0.402205,-inf,-inf,-inf,-inf,-inf,6.397435,9.827886,-inf,1.0,...,1.000,1.0,1.0,0.166976,0.037652,0.001091,1.458964e-07,7.642447e-13,1.556751e-27,2.337050e+00
696150.0,0.860414,-inf,-inf,-inf,-inf,-inf,5.889025,10.090964,-inf,1.0,...,0.000,0.0,0.0,0.225308,0.059291,0.043609,6.667146e-03,4.497944e-05,8.155879e-11,2.748065e-18
275937.0,1.236473,-inf,-inf,-534.732271,-325.212510,-570.617845,5.509491,9.061773,-inf,1.0,...,0.357,0.0,1.0,0.208543,0.063432,0.017128,7.098105e-04,1.062577e-06,3.534801e-10,3.537056e-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280847.0,0.891053,-inf,-inf,-inf,-inf,-inf,6.062024,9.828265,-inf,1.0,...,0.000,0.0,0.0,0.258833,0.064457,0.006125,8.689365e-06,2.941388e-10,1.745581e-22,0.000000e+00
459317.0,0.590972,-inf,-inf,-inf,-inf,-inf,6.066148,10.137624,-inf,1.0,...,0.520,0.0,1.0,0.143106,0.035783,0.001204,2.442851e-07,1.234837e-12,2.870293e-26,6.614997e-11
2234499.0,1.665527,-inf,-inf,9.328456,8.516454,-27.897028,6.638680,10.012461,-inf,1.0,...,1.000,1.0,1.0,1.121612,1.002890,0.793485,5.564541e-01,3.633511e-01,7.141296e-01,6.396150e-01
2285403.0,1.415895,-inf,-inf,-129.169707,-106.205792,-291.337477,7.311489,10.108510,-inf,1.0,...,0.673,0.0,1.0,0.313092,0.111736,0.079741,4.628320e-02,2.329982e-02,2.686336e-03,7.473821e-05
1340918.0,0.559531,-inf,-inf,-inf,-inf,-inf,6.177313,9.956582,-inf,1.0,...,0.879,0.0,1.0,0.914309,0.929842,0.973727,1.025997e+00,1.074485e+00,1.108942e+00,8.770791e-01

In [6]:
collated_eos_with_ntov = pd.read_csv(
    '../data/eos-draws-default/collated_np_all_post.csv',
    index_col='eos'
)
collated_eos['ntov'] = collated_eos_with_ntov['rhoc(M@Mmax)']

In [7]:
collated_eos

,Mmax,logweight_Fonseca_J0740,logweight_Antoniadis_J0348,logweight_Choudhury_J0437,logweight_Miller_J0030,logweight_Miller_J0740,logweight_GW170817,logweight_GW190425,logweight_total,prior_weight,...,pqcd_weight_ntov_X0.5_mu2.6,pqcd_weight_ntov_X2_mu2.6,pqcd_weight_04nsat_marg,pqcd_weight_05nsat_marg,pqcd_weight_06nsat_marg,pqcd_weight_07nsat_marg,pqcd_weight_08nsat_marg,pqcd_weight_10nsat_marg,pqcd_weight_ntov_marg,ntov
eos,,,,,,,,,,,,,,,,,,,,,
2265967.0,1.700984,-inf,-inf,9.139681,7.747685,-16.864775,6.864917,10.745082,-inf,1.0,...,1.0,1.0,1.178079,0.961522,0.877837,9.276641e-01,1.070579e+00,7.581512e-01,8.762803e-01,1.547739e+15
264698.0,1.590114,-inf,-inf,-149.884999,-179.692122,-182.080274,6.529798,8.000491,-inf,1.0,...,0.0,1.0,0.153030,0.067579,0.096838,6.046293e-02,2.867965e-02,6.772450e-03,4.011288e-04,3.107859e+15
1683176.0,0.402205,-inf,-inf,-inf,-inf,-inf,6.397435,9.827886,-inf,1.0,...,1.0,1.0,0.166976,0.037652,0.001091,1.458964e-07,7.642447e-13,1.556751e-27,2.337050e+00,3.500704e+14
696150.0,0.860414,-inf,-inf,-inf,-inf,-inf,5.889025,10.090964,-inf,1.0,...,0.0,0.0,0.225308,0.059291,0.043609,6.667146e-03,4.497944e-05,8.155879e-11,2.748065e-18,2.981789e+15
275937.0,1.236473,-inf,-inf,-534.732271,-325.212510,-570.617845,5.509491,9.061773,-inf,1.0,...,0.0,1.0,0.208543,0.063432,0.017128,7.098105e-04,1.062577e-06,3.534801e-10,3.537056e-12,3.360000e+15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280847.0,0.891053,-inf,-inf,-inf,-inf,-inf,6.062024,9.828265,-inf,1.0,...,0.0,0.0,0.258833,0.064457,0.006125,8.689365e-06,2.941388e-10,1.745581e-22,0.000000e+00,1.000000e+16
459317.0,0.590972,-inf,-inf,-inf,-inf,-inf,6.066148,10.137624,-inf,1.0,...,0.0,1.0,0.143106,0.035783,0.001204,2.442851e-07,1.234837e-12,2.870293e-26,6.614997e-11,2.036261e+15
2234499.0,1.665527,-inf,-inf,9.328456,8.516454,-27.897028,6.638680,10.012461,-inf,1.0,...,1.0,1.0,1.121612,1.002890,0.793485,5.564541e-01,3.633511e-01,7.141296e-01,6.396150e-01,1.768362e+15
2285403.0,1.415895,-inf,-inf,-129.169707,-106.205792,-291.337477,7.311489,10.108510,-inf,1.0,...,0.0,1.0,0.313092,0.111736,0.079741,4.628320e-02,2.329982e-02,2.686336e-03,7.473821e-05,3.360000e+15
1340918.0,0.559531,-inf,-inf,-inf,-inf,-inf,6.177313,9.956582,-inf,1.0,...,0.0,1.0,0.914309,0.929842,0.973727,1.025997e+00,1.074485e+00,1.108942e+00,8.770791e-01,3.360000e+15

In [8]:
collated_eos.to_csv('../data/eos-draws-default/eos-draws-default.csv')

When working with astro constraints we can filter out all the EOSs with zero weight to simplify things

In [9]:
nonzero_collated_eos = collated_eos[collated_eos.logweight_total > -np.inf]

In [10]:
len(nonzero_collated_eos)

79600

In [11]:
nonzero_collated_eos.iloc[0]

Mmax                              2.603362e+00
logweight_Fonseca_J0740          -4.721028e-01
logweight_Antoniadis_J0348       -4.721028e-01
logweight_Choudhury_J0437        -8.044066e+01
logweight_Miller_J0030            5.523424e+00
logweight_Miller_J0740            1.012106e+00
logweight_GW170817               -6.442459e+01
logweight_GW190425                8.740168e+00
logweight_total                  -1.305338e+02
prior_weight                      1.000000e+00
pqcd_weight_02nsat_Xmarg_mu2.6    1.000000e+00
pqcd_weight_02nsat_X0.5_mu2.6     1.000000e+00
pqcd_weight_02nsat_X2_mu2.6       1.000000e+00
pqcd_weight_03nsat_Xmarg_mu2.6    1.000000e+00
pqcd_weight_03nsat_X0.5_mu2.6     1.000000e+00
pqcd_weight_03nsat_X2_mu2.6       1.000000e+00
pqcd_weight_04nsat_Xmarg_mu2.6    1.000000e+00
pqcd_weight_04nsat_X0.5_mu2.6     1.000000e+00
pqcd_weight_04nsat_X2_mu2.6       1.000000e+00
pqcd_weight_05nsat_Xmarg_mu2.6    1.000000e+00
pqcd_weight_05nsat_X0.5_mu2.6     1.000000e+00
pqcd_weight_05nsat_X2_mu2.6       1.000000e+00
pqcd_weight_06nsat_Xmarg_mu2.6    1.000000e+00
pqcd_weight_06nsat_X0.5_mu2.6     1.000000e+00
pqcd_weight_06nsat_X2_mu2.6       1.000000e+00
pqcd_weight_07nsat_Xmarg_mu2.6    1.000000e+00
pqcd_weight_07nsat_X0.5_mu2.6     1.000000e+00
pqcd_weight_07nsat_X2_mu2.6       1.000000e+00
pqcd_weight_08nsat_Xmarg_mu2.6    1.000000e+00
pqcd_weight_08nsat_X0.5_mu2.6     1.000000e+00
pqcd_weight_08nsat_X2_mu2.6       1.000000e+00
pqcd_weight_09nsat_Xmarg_mu2.6    1.000000e+00
pqcd_weight_09nsat_X0.5_mu2.6     1.000000e+00
pqcd_weight_09nsat_X2_mu2.6       1.000000e+00
pqcd_weight_10nsat_Xmarg_mu2.6    1.000000e+00
pqcd_weight_10nsat_X0.5_mu2.6     1.000000e+00
pqcd_weight_10nsat_X2_mu2.6       1.000000e+00
pqcd_weight_ntov_Xmarg_mu2.6      1.000000e+00
pqcd_weight_ntov_X0.5_mu2.6       1.000000e+00
pqcd_weight_ntov_X2_mu2.6         1.000000e+00
pqcd_weight_04nsat_marg           7.430722e-01
pqcd_weight_05nsat_marg           6.773061e-01
pqcd_weight_06nsat_marg           6.476379e-01
pqcd_weight_07nsat_marg           6.298294e-01
pqcd_weight_08nsat_marg           5.701081e-01
pqcd_weight_10nsat_marg           3.903830e-01
pqcd_weight_ntov_marg             7.630664e-01
ntov                              1.027698e+15
Name: 1295491.0, dtype: float64

In [12]:
nonzero_collated_eos.iloc[0].logweight_total

np.float64(-130.533758835973)

In [13]:
nonzero_collated_eos.iloc[0].logweight_Miller_J0030 + \
    nonzero_collated_eos.iloc[0].logweight_Miller_J0740 + \
    nonzero_collated_eos.iloc[0].logweight_Choudhury_J0437 + \
    nonzero_collated_eos.iloc[0].logweight_Antoniadis_J0348 + \
    nonzero_collated_eos.iloc[0].logweight_Fonseca_J0740 + \
    nonzero_collated_eos.iloc[0].logweight_GW170817 + \
    nonzero_collated_eos.iloc[0].logweight_GW190425

np.float64(-130.53375883597298)

In [14]:
# Save the collated EOSs with the combined weights
nonzero_collated_eos.to_csv('../data/eos-draws-default/eos-draws-default-nonzero-astro.csv')